### ISSUE TITLE
当 whenMvel 方法执行了不正确格式的 mvel 表达式时，抛出的是 NullPointerException 错误

### ISSUE THREAD

**Issue by RubinCarter** [hekailiang/squirrel#120]
大大好
       我们在使用 builder.externalTransition().from().to().on().whenMvel() 时，填入的 mvel 表达式有语法错误时，提示的错误时 NullPointerException 错误，不便于排查问题，具体的日志如下：
java.lang.NullPointerException
	at org.squirrelframework.foundation.fsm.impl.MvelConditionImpl.isSatisfied(MvelConditionImpl.java:47)
	at org.squirrelframework.foundation.fsm.impl.TransitionImpl.internalFire(TransitionImpl.java:193)
	at org.squirrelframework.foundation.fsm.impl.StateImpl.internalFire(StateImpl.java:419)
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.processEvent(AbstractStateMachine.java:161)
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.processEvents(AbstractStateMachine.java:215)
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.internalFire(AbstractStateMachine.java:248)
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.fire(AbstractStateMachine.java:268)
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.fire(AbstractStateMachine.java:279)

![image](https://user-images.githubusercontent.com/13096279/94220636-023de780-ff1c-11ea-88e1-0ff45dd177f4.png)

**Comment by RubinCarter** [comment]
看到master已经修复了
